services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        environment:
            - DB_HOST=db
            - DB_PORT=5432
            - DB_NAME_FILE=/run/secrets/db-name
            - DB_USER_FILE=/run/secrets/db-user
            - DB_PASSWORD_FILE=/run/secrets/db-password
        depends_on:
            - db
        networks:
            - crud-app
        secrets:
            - db-name
            - db-user
            - db-password
        user: "${DOCKER_USER}"
        working_dir: /app
        volumes:
            - ./:/app

    nginx:
        image: nginx:alpine3.17
        depends_on:
            - app
        networks:
            - crud-app
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/config.nginx:/etc/nginx/conf.d/default.conf:ro

    phpunit:
        build:
            context: .
            dockerfile: Dockerfile
            target: app
        entrypoint: [ "/usr/local/bin/php" ]
        command: [ "/app/vendor/bin/phpunit" ]
        working_dir: "/app"
        user: "${DOCKER_USER}"
        volumes:
            - ./:/app

    db:
        image: postgres:16-alpine
        environment:
            - PGDATA=/var/lib/postgresql/data/pgdata
            - POSTGRES_db_FILE=/run/secrets/db-name
            - POSTGRES_USER_FILE=/run/secrets/db-user
            - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
        expose:
            - 5432
        ports:
            - "127.0.0.1:5432:5432"
        healthcheck:
            test: [ "CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}" ]
            timeout: 5s
            retries: 5
            start_period: 60s
        networks:
            - crud-app
        secrets:
            - db-user
            - db-password
        volumes:
            - "./data/db:/var/lib/postgresql/data"

networks:
    crud-app:
        name: crud-app

secrets:
    db-name:
        file: docker/db/secrets/db
    db-user:
        file: docker/db/secrets/user
    db-password:
        file: docker/db/secrets/password
